#!/bin/bash
#PBS -l nodes=1:ppn=16
#PBS -l walltime=02:00:00

# Copyright (c) 2020 brainlife.io at University of Texas at Austin and Indiana University
# 
# This is the main file run by the brainlife.io orchestration system
#
# Author: Franco Pestilli

# parse config.json to load the input parameters needed for the app
t1=$(jq -r .t1 config.json)

# run the actual python code
./main.m $t1
